name: sleep 10s
on: push

concurrency: 10

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: sleeping for 10 sec
        run: sleep 10

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"