name: sub-seq1
on:
#  push:
#    paths:
#      - action-a/**
#      - config/**
#    branches:
#      - main
  workflow_run:
    workflows: ["wf-main"]

jobs:
  test:
    name: echo test
    runs-on: ubuntu-latest
    steps:
       - name: Checkout the code
         uses: actions/checkout@v2
          # https://github.community/t/workflow-run-not-working-as-expected/139342/4
          # Workflow_run can trigger workflow only on the default branch (master)
          # It is workaround for workflow_run trigger
          # to checkout not the default branch but the last commit
          # from the branch which triggered this workflow
         with:
           ref: ${{ github.event.workflow_run.head_sha }}
       - name: Set PP_IMAGE_TAG and PP_IMAGE env used in the next steps
         uses: actions/checkout@v2
         with:
           ref: ${{ github.event.workflow_run.head_sha }}
       - name: Set PP_IMAGE_TAG and PP_IMAGE env used in the next steps
         run: |
           git_hash=$(git rev-parse --short "$GITHUB_SHA") &&
           echo new_$git_hash
