name: sub-seq1
on:
#  push:
#    paths:
#      - action-a/**
#      - config/**
#    branches:
#      - main
  workflow_run:
    workflows: ["wf-main", "env"]

concurrency: wait


jobs:
  test:
    name: echo test
    runs-on: ubuntu-latest
    steps:
       - name: Set PP_IMAGE_TAG and PP_IMAGE env used in the next steps
         uses: actions/checkout@v2
         with:
           ref: ${{ github.event.workflow_run.head_sha }}
       - name: Set PP_IMAGE_TAG and PP_IMAGE env used in the next steps
         run: |
           git_hash=$(git rev-parse --short "$GITHUB_SHA") &&
           echo new_$git_hash
