name: sub-seq1
on:
#  push:
#    paths:
#      - action-a/**
#      - config/**
#    # AND
#    branches:
#      - main
  # AND
  workflow_run:
    paths:
      - action-a/**
      - config/**
    branches:
      - main
    workflows: ["wf-main", "env"]
    types:
      - completed

jobs:
  test:
    name: echo test
    runs-on: ubuntu-latest
    steps:
      - name: test title
        run: echo testmain