name: sub-seq1
on:
  push:
    paths:
      - action-a/**
      - config/**

jobs:
  test:
    name: echo test
    runs-on: ubuntu-latest
    steps:
      - name: test title
        run: echo testmain